# Generated by Django 4.1.7 on 2023-02-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist_table',
            name='work',
            field=models.ManyToManyField(max_length=50, to='assignment.work_table'),
        ),
    ]
