# Generated by Django 4.1.7 on 2023-02-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_artist_table_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_table',
            name='work_type',
            field=models.CharField(choices=[('YOUTUBE', 'YOUTUBE'), ('YOUTUBE', 'INSTAGRAM'), ('YOUTUBE', 'OTHERS')], default='None', max_length=30),
        ),
    ]
