# Generated by Django 4.1.7 on 2023-02-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_alter_work_table_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_table',
            name='work_type',
            field=models.CharField(choices=[('Youtube', 'YOUTUBE'), ('Instagram', 'INSTAGRAM'), ('Others', 'OTHERS')], default='None', max_length=30),
        ),
    ]
